# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Windows Container App to Azure App Service

on:
  push:
    branches:
      - master
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: azure/docker-login@v1
        with:
          login-server: yoonaohacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0E255FB695D94CAAB965B9722D6E30C2 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_0AA3010AE54D43DD8C7E508A7AF46B8C }}

      - name: Build and Push container to registry
        run: |
          docker build -t yoonaohacr.azurecr.io/test-win-container:${{ github.sha }} .
          docker push yoonaohacr.azurecr.io/test-win-container:${{ github.sha }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_571F8E96948E47D49A27E9C12BC2DE74 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6BC5B7B306554E3FAB510D794AA570B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF57623A9FD9426D910C9178254ECFD9 }}

      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'yo-webapp-win-container'
          slot-name: 'Production'
          images: 'yoonaohacr.azurecr.io/test-win-container:${{ github.sha }}'
          
